/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SuperAdminRouteRouteImport } from './routes/super-admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as SatgasIndexRouteImport } from './routes/satgas/index'
import { Route as ManagerIndexRouteImport } from './routes/manager/index'
import { Route as KasirIndexRouteImport } from './routes/kasir/index'
import { Route as ClearUpIndexRouteImport } from './routes/clear-up/index'
import { Route as AmIndexRouteImport } from './routes/am/index'
import { Route as SuperAdminStaffAccountsRouteImport } from './routes/super-admin/staff-accounts'
import { Route as SuperAdminRecoveryRouteImport } from './routes/super-admin/recovery'
import { Route as SuperAdminManagersRouteImport } from './routes/super-admin/managers'
import { Route as SuperAdminHistoryRouteImport } from './routes/super-admin/history'
import { Route as SuperAdminEsbExportRouteImport } from './routes/super-admin/esb-export'
import { Route as SuperAdminErrorLogRouteImport } from './routes/super-admin/error-log'
import { Route as SuperAdminAuditRouteImport } from './routes/super-admin/audit'
import { Route as SuperAdminAudioRouteImport } from './routes/super-admin/audio'
import { Route as SuperAdminAreaManagersRouteImport } from './routes/super-admin/area-managers'
import { Route as SuperAdminAcceptRouteImport } from './routes/super-admin/accept'
import { Route as QDeclineRouteImport } from './routes/q/decline'
import { Route as QTokenRouteImport } from './routes/q/$token'
import { Route as ManagerLoginRouteImport } from './routes/manager/login'
import { Route as ManagerForgotRouteImport } from './routes/manager/forgot'
import { Route as AmForgotRouteImport } from './routes/am/forgot'
import { Route as SuperAdminRestaurantsIndexRouteImport } from './routes/super-admin/restaurants/index'
import { Route as SuperAdminRestaurantsIdRouteImport } from './routes/super-admin/restaurants/$id'
import { Route as ApiAudioAudioIdRouteImport } from './routes/api/audio/$audioId'
import { Route as ApiSuperAdminQrExportBatchIdFormatRouteImport } from './routes/api/super-admin/qr-export/$batchId/$format'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRouteRoute = SuperAdminRouteRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SatgasIndexRoute = SatgasIndexRouteImport.update({
  id: '/satgas/',
  path: '/satgas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const KasirIndexRoute = KasirIndexRouteImport.update({
  id: '/kasir/',
  path: '/kasir/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClearUpIndexRoute = ClearUpIndexRouteImport.update({
  id: '/clear-up/',
  path: '/clear-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmIndexRoute = AmIndexRouteImport.update({
  id: '/am/',
  path: '/am/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminStaffAccountsRoute = SuperAdminStaffAccountsRouteImport.update({
  id: '/staff-accounts',
  path: '/staff-accounts',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminRecoveryRoute = SuperAdminRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminManagersRoute = SuperAdminManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminHistoryRoute = SuperAdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminEsbExportRoute = SuperAdminEsbExportRouteImport.update({
  id: '/esb-export',
  path: '/esb-export',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminErrorLogRoute = SuperAdminErrorLogRouteImport.update({
  id: '/error-log',
  path: '/error-log',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminAuditRoute = SuperAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminAudioRoute = SuperAdminAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminAreaManagersRoute = SuperAdminAreaManagersRouteImport.update({
  id: '/area-managers',
  path: '/area-managers',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const SuperAdminAcceptRoute = SuperAdminAcceptRouteImport.update({
  id: '/accept',
  path: '/accept',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const QDeclineRoute = QDeclineRouteImport.update({
  id: '/q/decline',
  path: '/q/decline',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLoginRoute = ManagerLoginRouteImport.update({
  id: '/manager/login',
  path: '/manager/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerForgotRoute = ManagerForgotRouteImport.update({
  id: '/manager/forgot',
  path: '/manager/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const AmForgotRoute = AmForgotRouteImport.update({
  id: '/am/forgot',
  path: '/am/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRestaurantsIndexRoute =
  SuperAdminRestaurantsIndexRouteImport.update({
    id: '/restaurants/',
    path: '/restaurants/',
    getParentRoute: () => SuperAdminRouteRoute,
  } as any)
const SuperAdminRestaurantsIdRoute = SuperAdminRestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => SuperAdminRouteRoute,
} as any)
const ApiAudioAudioIdRoute = ApiAudioAudioIdRouteImport.update({
  id: '/api/audio/$audioId',
  path: '/api/audio/$audioId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuperAdminQrExportBatchIdFormatRoute =
  ApiSuperAdminQrExportBatchIdFormatRouteImport.update({
    id: '/api/super-admin/qr-export/$batchId/$format',
    path: '/api/super-admin/qr-export/$batchId/$format',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/am/forgot': typeof AmForgotRoute
  '/manager/forgot': typeof ManagerForgotRoute
  '/manager/login': typeof ManagerLoginRoute
  '/q/$token': typeof QTokenRoute
  '/q/decline': typeof QDeclineRoute
  '/super-admin/accept': typeof SuperAdminAcceptRoute
  '/super-admin/area-managers': typeof SuperAdminAreaManagersRoute
  '/super-admin/audio': typeof SuperAdminAudioRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/error-log': typeof SuperAdminErrorLogRoute
  '/super-admin/esb-export': typeof SuperAdminEsbExportRoute
  '/super-admin/history': typeof SuperAdminHistoryRoute
  '/super-admin/managers': typeof SuperAdminManagersRoute
  '/super-admin/recovery': typeof SuperAdminRecoveryRoute
  '/super-admin/staff-accounts': typeof SuperAdminStaffAccountsRoute
  '/am/': typeof AmIndexRoute
  '/clear-up/': typeof ClearUpIndexRoute
  '/kasir/': typeof KasirIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/satgas/': typeof SatgasIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/api/audio/$audioId': typeof ApiAudioAudioIdRoute
  '/super-admin/restaurants/$id': typeof SuperAdminRestaurantsIdRoute
  '/super-admin/restaurants/': typeof SuperAdminRestaurantsIndexRoute
  '/api/super-admin/qr-export/$batchId/$format': typeof ApiSuperAdminQrExportBatchIdFormatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/am/forgot': typeof AmForgotRoute
  '/manager/forgot': typeof ManagerForgotRoute
  '/manager/login': typeof ManagerLoginRoute
  '/q/$token': typeof QTokenRoute
  '/q/decline': typeof QDeclineRoute
  '/super-admin/accept': typeof SuperAdminAcceptRoute
  '/super-admin/area-managers': typeof SuperAdminAreaManagersRoute
  '/super-admin/audio': typeof SuperAdminAudioRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/error-log': typeof SuperAdminErrorLogRoute
  '/super-admin/esb-export': typeof SuperAdminEsbExportRoute
  '/super-admin/history': typeof SuperAdminHistoryRoute
  '/super-admin/managers': typeof SuperAdminManagersRoute
  '/super-admin/recovery': typeof SuperAdminRecoveryRoute
  '/super-admin/staff-accounts': typeof SuperAdminStaffAccountsRoute
  '/am': typeof AmIndexRoute
  '/clear-up': typeof ClearUpIndexRoute
  '/kasir': typeof KasirIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/satgas': typeof SatgasIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
  '/api/audio/$audioId': typeof ApiAudioAudioIdRoute
  '/super-admin/restaurants/$id': typeof SuperAdminRestaurantsIdRoute
  '/super-admin/restaurants': typeof SuperAdminRestaurantsIndexRoute
  '/api/super-admin/qr-export/$batchId/$format': typeof ApiSuperAdminQrExportBatchIdFormatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/super-admin': typeof SuperAdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/am/forgot': typeof AmForgotRoute
  '/manager/forgot': typeof ManagerForgotRoute
  '/manager/login': typeof ManagerLoginRoute
  '/q/$token': typeof QTokenRoute
  '/q/decline': typeof QDeclineRoute
  '/super-admin/accept': typeof SuperAdminAcceptRoute
  '/super-admin/area-managers': typeof SuperAdminAreaManagersRoute
  '/super-admin/audio': typeof SuperAdminAudioRoute
  '/super-admin/audit': typeof SuperAdminAuditRoute
  '/super-admin/error-log': typeof SuperAdminErrorLogRoute
  '/super-admin/esb-export': typeof SuperAdminEsbExportRoute
  '/super-admin/history': typeof SuperAdminHistoryRoute
  '/super-admin/managers': typeof SuperAdminManagersRoute
  '/super-admin/recovery': typeof SuperAdminRecoveryRoute
  '/super-admin/staff-accounts': typeof SuperAdminStaffAccountsRoute
  '/am/': typeof AmIndexRoute
  '/clear-up/': typeof ClearUpIndexRoute
  '/kasir/': typeof KasirIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/satgas/': typeof SatgasIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
  '/api/audio/$audioId': typeof ApiAudioAudioIdRoute
  '/super-admin/restaurants/$id': typeof SuperAdminRestaurantsIdRoute
  '/super-admin/restaurants/': typeof SuperAdminRestaurantsIndexRoute
  '/api/super-admin/qr-export/$batchId/$format': typeof ApiSuperAdminQrExportBatchIdFormatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/super-admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/am/forgot'
    | '/manager/forgot'
    | '/manager/login'
    | '/q/$token'
    | '/q/decline'
    | '/super-admin/accept'
    | '/super-admin/area-managers'
    | '/super-admin/audio'
    | '/super-admin/audit'
    | '/super-admin/error-log'
    | '/super-admin/esb-export'
    | '/super-admin/history'
    | '/super-admin/managers'
    | '/super-admin/recovery'
    | '/super-admin/staff-accounts'
    | '/am/'
    | '/clear-up/'
    | '/kasir/'
    | '/manager/'
    | '/satgas/'
    | '/super-admin/'
    | '/api/audio/$audioId'
    | '/super-admin/restaurants/$id'
    | '/super-admin/restaurants/'
    | '/api/super-admin/qr-export/$batchId/$format'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/am/forgot'
    | '/manager/forgot'
    | '/manager/login'
    | '/q/$token'
    | '/q/decline'
    | '/super-admin/accept'
    | '/super-admin/area-managers'
    | '/super-admin/audio'
    | '/super-admin/audit'
    | '/super-admin/error-log'
    | '/super-admin/esb-export'
    | '/super-admin/history'
    | '/super-admin/managers'
    | '/super-admin/recovery'
    | '/super-admin/staff-accounts'
    | '/am'
    | '/clear-up'
    | '/kasir'
    | '/manager'
    | '/satgas'
    | '/super-admin'
    | '/api/audio/$audioId'
    | '/super-admin/restaurants/$id'
    | '/super-admin/restaurants'
    | '/api/super-admin/qr-export/$batchId/$format'
  id:
    | '__root__'
    | '/'
    | '/super-admin'
    | '/about'
    | '/contact'
    | '/faq'
    | '/help'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/am/forgot'
    | '/manager/forgot'
    | '/manager/login'
    | '/q/$token'
    | '/q/decline'
    | '/super-admin/accept'
    | '/super-admin/area-managers'
    | '/super-admin/audio'
    | '/super-admin/audit'
    | '/super-admin/error-log'
    | '/super-admin/esb-export'
    | '/super-admin/history'
    | '/super-admin/managers'
    | '/super-admin/recovery'
    | '/super-admin/staff-accounts'
    | '/am/'
    | '/clear-up/'
    | '/kasir/'
    | '/manager/'
    | '/satgas/'
    | '/super-admin/'
    | '/api/audio/$audioId'
    | '/super-admin/restaurants/$id'
    | '/super-admin/restaurants/'
    | '/api/super-admin/qr-export/$batchId/$format'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuperAdminRouteRoute: typeof SuperAdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  AmForgotRoute: typeof AmForgotRoute
  ManagerForgotRoute: typeof ManagerForgotRoute
  ManagerLoginRoute: typeof ManagerLoginRoute
  QTokenRoute: typeof QTokenRoute
  QDeclineRoute: typeof QDeclineRoute
  AmIndexRoute: typeof AmIndexRoute
  ClearUpIndexRoute: typeof ClearUpIndexRoute
  KasirIndexRoute: typeof KasirIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  SatgasIndexRoute: typeof SatgasIndexRoute
  ApiAudioAudioIdRoute: typeof ApiAudioAudioIdRoute
  ApiSuperAdminQrExportBatchIdFormatRoute: typeof ApiSuperAdminQrExportBatchIdFormatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/satgas/': {
      id: '/satgas/'
      path: '/satgas'
      fullPath: '/satgas/'
      preLoaderRoute: typeof SatgasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasir/': {
      id: '/kasir/'
      path: '/kasir'
      fullPath: '/kasir/'
      preLoaderRoute: typeof KasirIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clear-up/': {
      id: '/clear-up/'
      path: '/clear-up'
      fullPath: '/clear-up/'
      preLoaderRoute: typeof ClearUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am/': {
      id: '/am/'
      path: '/am'
      fullPath: '/am/'
      preLoaderRoute: typeof AmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/staff-accounts': {
      id: '/super-admin/staff-accounts'
      path: '/staff-accounts'
      fullPath: '/super-admin/staff-accounts'
      preLoaderRoute: typeof SuperAdminStaffAccountsRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/recovery': {
      id: '/super-admin/recovery'
      path: '/recovery'
      fullPath: '/super-admin/recovery'
      preLoaderRoute: typeof SuperAdminRecoveryRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/managers': {
      id: '/super-admin/managers'
      path: '/managers'
      fullPath: '/super-admin/managers'
      preLoaderRoute: typeof SuperAdminManagersRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/history': {
      id: '/super-admin/history'
      path: '/history'
      fullPath: '/super-admin/history'
      preLoaderRoute: typeof SuperAdminHistoryRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/esb-export': {
      id: '/super-admin/esb-export'
      path: '/esb-export'
      fullPath: '/super-admin/esb-export'
      preLoaderRoute: typeof SuperAdminEsbExportRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/error-log': {
      id: '/super-admin/error-log'
      path: '/error-log'
      fullPath: '/super-admin/error-log'
      preLoaderRoute: typeof SuperAdminErrorLogRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/audit': {
      id: '/super-admin/audit'
      path: '/audit'
      fullPath: '/super-admin/audit'
      preLoaderRoute: typeof SuperAdminAuditRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/audio': {
      id: '/super-admin/audio'
      path: '/audio'
      fullPath: '/super-admin/audio'
      preLoaderRoute: typeof SuperAdminAudioRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/area-managers': {
      id: '/super-admin/area-managers'
      path: '/area-managers'
      fullPath: '/super-admin/area-managers'
      preLoaderRoute: typeof SuperAdminAreaManagersRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/accept': {
      id: '/super-admin/accept'
      path: '/accept'
      fullPath: '/super-admin/accept'
      preLoaderRoute: typeof SuperAdminAcceptRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/q/decline': {
      id: '/q/decline'
      path: '/q/decline'
      fullPath: '/q/decline'
      preLoaderRoute: typeof QDeclineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/login': {
      id: '/manager/login'
      path: '/manager/login'
      fullPath: '/manager/login'
      preLoaderRoute: typeof ManagerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/forgot': {
      id: '/manager/forgot'
      path: '/manager/forgot'
      fullPath: '/manager/forgot'
      preLoaderRoute: typeof ManagerForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/am/forgot': {
      id: '/am/forgot'
      path: '/am/forgot'
      fullPath: '/am/forgot'
      preLoaderRoute: typeof AmForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/restaurants/': {
      id: '/super-admin/restaurants/'
      path: '/restaurants'
      fullPath: '/super-admin/restaurants/'
      preLoaderRoute: typeof SuperAdminRestaurantsIndexRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/super-admin/restaurants/$id': {
      id: '/super-admin/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/super-admin/restaurants/$id'
      preLoaderRoute: typeof SuperAdminRestaurantsIdRouteImport
      parentRoute: typeof SuperAdminRouteRoute
    }
    '/api/audio/$audioId': {
      id: '/api/audio/$audioId'
      path: '/api/audio/$audioId'
      fullPath: '/api/audio/$audioId'
      preLoaderRoute: typeof ApiAudioAudioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/super-admin/qr-export/$batchId/$format': {
      id: '/api/super-admin/qr-export/$batchId/$format'
      path: '/api/super-admin/qr-export/$batchId/$format'
      fullPath: '/api/super-admin/qr-export/$batchId/$format'
      preLoaderRoute: typeof ApiSuperAdminQrExportBatchIdFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuperAdminRouteRouteChildren {
  SuperAdminAcceptRoute: typeof SuperAdminAcceptRoute
  SuperAdminAreaManagersRoute: typeof SuperAdminAreaManagersRoute
  SuperAdminAudioRoute: typeof SuperAdminAudioRoute
  SuperAdminAuditRoute: typeof SuperAdminAuditRoute
  SuperAdminErrorLogRoute: typeof SuperAdminErrorLogRoute
  SuperAdminEsbExportRoute: typeof SuperAdminEsbExportRoute
  SuperAdminHistoryRoute: typeof SuperAdminHistoryRoute
  SuperAdminManagersRoute: typeof SuperAdminManagersRoute
  SuperAdminRecoveryRoute: typeof SuperAdminRecoveryRoute
  SuperAdminStaffAccountsRoute: typeof SuperAdminStaffAccountsRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
  SuperAdminRestaurantsIdRoute: typeof SuperAdminRestaurantsIdRoute
  SuperAdminRestaurantsIndexRoute: typeof SuperAdminRestaurantsIndexRoute
}

const SuperAdminRouteRouteChildren: SuperAdminRouteRouteChildren = {
  SuperAdminAcceptRoute: SuperAdminAcceptRoute,
  SuperAdminAreaManagersRoute: SuperAdminAreaManagersRoute,
  SuperAdminAudioRoute: SuperAdminAudioRoute,
  SuperAdminAuditRoute: SuperAdminAuditRoute,
  SuperAdminErrorLogRoute: SuperAdminErrorLogRoute,
  SuperAdminEsbExportRoute: SuperAdminEsbExportRoute,
  SuperAdminHistoryRoute: SuperAdminHistoryRoute,
  SuperAdminManagersRoute: SuperAdminManagersRoute,
  SuperAdminRecoveryRoute: SuperAdminRecoveryRoute,
  SuperAdminStaffAccountsRoute: SuperAdminStaffAccountsRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
  SuperAdminRestaurantsIdRoute: SuperAdminRestaurantsIdRoute,
  SuperAdminRestaurantsIndexRoute: SuperAdminRestaurantsIndexRoute,
}

const SuperAdminRouteRouteWithChildren = SuperAdminRouteRoute._addFileChildren(
  SuperAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuperAdminRouteRoute: SuperAdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  AmForgotRoute: AmForgotRoute,
  ManagerForgotRoute: ManagerForgotRoute,
  ManagerLoginRoute: ManagerLoginRoute,
  QTokenRoute: QTokenRoute,
  QDeclineRoute: QDeclineRoute,
  AmIndexRoute: AmIndexRoute,
  ClearUpIndexRoute: ClearUpIndexRoute,
  KasirIndexRoute: KasirIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  SatgasIndexRoute: SatgasIndexRoute,
  ApiAudioAudioIdRoute: ApiAudioAudioIdRoute,
  ApiSuperAdminQrExportBatchIdFormatRoute:
    ApiSuperAdminQrExportBatchIdFormatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
